### ISSUE TITLE
Make natural order comparator explicit

### ISSUE THREAD

**Issue by bryce-carson** [koddyrae/COMP2503-A3#1]
https://github.com/koddyrae/COMP2503-A3/blob/f30d3c589878a6fe27cecfa7ae000a9317878bd4/src/A3.java#L10-L12

Let's use an explicit natural order comparator in the initialization of the first BST. The natural order comparator just calls the compareTo method, so there's no real change other than style, here.

**Comment by koddyrae** [comment]
the intialization of all the bsts are straight from her starter code so not sure if we should actually change it
