### ISSUE TITLE
Sentinel variable must be reinitialized before use

### ISSUE THREAD

**Issue by bryce-carson** [koddyrae/COMP2503-A3#4]
https://github.com/koddyrae/COMP2503-A3/blob/0283208bd817fbdd326561946e2ddeac5b458546/src/A3.java#L71

When I wrote the loop for the first set of printing ten things, I initialized a sentinel variable that is decremented within the loop body (`i=10;`).

The same sentinel variable may be used, @koddyrae, as you are doing, but it must be given a new value prior to the test in the second while loop that uses it (`i=10; // Reset sentinel.`).

**Comment by koddyrae** [comment]
bet ill fix it right away
